export const SET_USER = 'SET_USER';
export const UPDATE_TOKENS = 'UPDATE_TOKENS';
export const EXIT_USER = 'EXIT_USER';
export const ADD_RECEIVED_INVITE = 'ADD_RECEIVED_INVITE';
export const REMOVE_RECEIVED_INVITE = 'REMOVE_RECEIVED_INVITE';
export const ADD_SENT_INVITE = 'ADD_SENT_INVITE';
export const REMOVE_SENT_INVITE = 'REMOVE_SENT_INVITE';
